[build]
builder = "nixpacks"

[deploy]
startCommand = "node run-migrate.js && node run-seed.js && node src/index.js"
healthcheckPath = "/health"
healthcheckTimeout = 60
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
